name: MvvMushroomHelper
author: michaelmvv
version: 1
description:Place mushrooms EZ!
main: michaelmvv.mushroom.MvvPlugin
commands:
  ToggleMushroom:
    description: Toggles Mushroom placing
    permission: mushroom.toggle
    permission-message: No Permission
  MushroomUpdateCheck:
    description: Check for MvvMushroomHelper Updates
    permission: mushroom.updatecheck
    permission-message: No Permission